// @generated by protobuf-ts 2.0.0-alpha.12 with parameters server_generic,client_none
// @generated from protobuf file "service-chat.proto" (package "spec", syntax proto3)
// tslint:disable
import { PostResponse } from "./service-chat";
import { PostRequest } from "./service-chat";
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
import { ChatEvent } from "./service-chat";
import { JoinRequest } from "./service-chat";
/**
 * @generated from protobuf service spec.ChatService
 */
export interface IChatService {
    /**
     * returns a response header "x-token" to authorize Post() calls.
     * streams all chat messages.
     *
     * @generated from protobuf rpc: Join(spec.JoinRequest) returns (stream spec.ChatEvent);
     */
    join(request: JoinRequest, responses: RpcInputStream<ChatEvent>, context: ServerCallContext): Promise<void>;
    /**
     * post a message to the chat.
     * must set "x-token" request header obtained from Join().
     *
     * @generated from protobuf rpc: Post(spec.PostRequest) returns (spec.PostResponse);
     */
    post(request: PostRequest, context: ServerCallContext): Promise<PostResponse>;
}
