// @generated by protobuf-ts 2.2.1 with parameter server_generic,client_none,generate_dependencies,optimize_code_size
// @generated from protobuf file "service-example.proto" (package "spec", syntax proto3)
// tslint:disable
import { RpcOutputStream } from "@chippercash/protobuf-runtime-rpc";
import { RpcInputStream } from "@chippercash/protobuf-runtime-rpc";
import { ExampleResponse } from "./service-example";
import { ExampleRequest } from "./service-example";
import { ServerCallContext } from "@chippercash/protobuf-runtime-rpc";
/**
 * @generated from protobuf service spec.ExampleService
 */
export interface IExampleService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: Unary(spec.ExampleRequest) returns (spec.ExampleResponse);
     */
    unary(request: ExampleRequest, context: T): Promise<ExampleResponse>;
    /**
     * @generated from protobuf rpc: ServerStream(spec.ExampleRequest) returns (stream spec.ExampleResponse);
     */
    serverStream(request: ExampleRequest, responses: RpcInputStream<ExampleResponse>, context: T): Promise<void>;
    /**
     * @generated from protobuf rpc: ClientStream(stream spec.ExampleRequest) returns (spec.ExampleResponse);
     */
    clientStream(requests: RpcOutputStream<ExampleRequest>, context: T): Promise<ExampleResponse>;
    /**
     * @generated from protobuf rpc: Bidi(stream spec.ExampleRequest) returns (stream spec.ExampleResponse);
     */
    bidi(requests: RpcOutputStream<ExampleRequest>, responses: RpcInputStream<ExampleResponse>, context: T): Promise<void>;
}
