// @generated by protobuf-ts 2.4.0 with parameter server_grpc1,client_none,optimize_code_size
// @generated from protobuf file "service-example.proto" (package "spec", syntax proto3)
// tslint:disable
import { ExampleResponse } from "./service-example";
import { ExampleRequest } from "./service-example";
import type * as grpc from "@grpc/grpc-js";
/**
 * @generated from protobuf service spec.ExampleService
 */
export interface IExampleService extends grpc.UntypedServiceImplementation {
    /**
     * @generated from protobuf rpc: Unary(spec.ExampleRequest) returns (spec.ExampleResponse);
     */
    unary: grpc.handleUnaryCall<ExampleRequest, ExampleResponse>;
    /**
     * @generated from protobuf rpc: ServerStream(spec.ExampleRequest) returns (stream spec.ExampleResponse);
     */
    serverStream: grpc.handleServerStreamingCall<ExampleRequest, ExampleResponse>;
    /**
     * @generated from protobuf rpc: ClientStream(stream spec.ExampleRequest) returns (spec.ExampleResponse);
     */
    clientStream: grpc.handleClientStreamingCall<ExampleRequest, ExampleResponse>;
    /**
     * @generated from protobuf rpc: Bidi(stream spec.ExampleRequest) returns (stream spec.ExampleResponse);
     */
    bidi: grpc.handleBidiStreamingCall<ExampleRequest, ExampleResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service spec.ExampleService.
 *
 * Usage: Implement the interface IExampleService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IExampleService = ...
 * server.addService(exampleServiceDefinition, service);
 * ```
 */
export const exampleServiceDefinition: grpc.ServiceDefinition<IExampleService> = {
    unary: {
        path: "/spec.ExampleService/Unary",
        originalName: "Unary",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => ExampleResponse.fromBinary(bytes),
        requestDeserialize: bytes => ExampleRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ExampleResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ExampleRequest.toBinary(value))
    },
    serverStream: {
        path: "/spec.ExampleService/ServerStream",
        originalName: "ServerStream",
        requestStream: false,
        responseStream: true,
        responseDeserialize: bytes => ExampleResponse.fromBinary(bytes),
        requestDeserialize: bytes => ExampleRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ExampleResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ExampleRequest.toBinary(value))
    },
    clientStream: {
        path: "/spec.ExampleService/ClientStream",
        originalName: "ClientStream",
        requestStream: true,
        responseStream: false,
        responseDeserialize: bytes => ExampleResponse.fromBinary(bytes),
        requestDeserialize: bytes => ExampleRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ExampleResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ExampleRequest.toBinary(value))
    },
    bidi: {
        path: "/spec.ExampleService/Bidi",
        originalName: "Bidi",
        requestStream: true,
        responseStream: true,
        responseDeserialize: bytes => ExampleResponse.fromBinary(bytes),
        requestDeserialize: bytes => ExampleRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ExampleResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ExampleRequest.toBinary(value))
    }
};
